# Generated by Django 5.2.3 on 2025-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
