# Generated by Django 5.2.3 on 2025-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_meeting', '0002_contribution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
